"""Initial schema

Revision ID: dacf330cafab
Revises: 
Create Date: 2026-07-11 19:58:51.307794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacf330cafab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='alert_severity'), nullable=False),
    sa.Column('alert_type', sa.Enum('incident', 'ticket', 'system', name='alert_type'), nullable=False),
    sa.Column('reference_id', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_reference_id'), 'alerts', ['reference_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_type_severity', 'alerts', ['alert_type', 'severity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'user', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_created_at', 'users', ['role', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('log_snippet', sa.Text(), nullable=True),
    sa.Column('incident_ref', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolution_steps', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_history_id'), 'ai_history', ['id'], unique=False)
    op.create_index(op.f('ix_ai_history_user_id'), 'ai_history', ['user_id'], unique=False)
    op.create_table('log_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'parsed', 'failed', name='log_status'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_log_files_file_type'), 'log_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_log_files_id'), 'log_files', ['id'], unique=False)
    op.create_index(op.f('ix_log_files_status'), 'log_files', ['status'], unique=False)
    op.create_index('ix_log_files_status_created_at', 'log_files', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_log_files_uploaded_by'), 'log_files', ['uploaded_by'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG', 'UNKNOWN', name='entry_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_log_file_id'), 'log_entries', ['log_file_id'], unique=False)
    op.create_index(op.f('ix_log_entries_severity'), 'log_entries', ['severity'], unique=False)
    op.create_index('ix_log_entries_severity_log_file', 'log_entries', ['severity', 'log_file_id'], unique=False)
    op.create_index(op.f('ix_log_entries_source'), 'log_entries', ['source'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.Enum('AUTH_FAILURE', 'TOKEN_EXPIRED', 'API_TIMEOUT', 'DATABASE_CONNECTION_ERROR', 'SSL_HANDSHAKE_FAILURE', 'EMAIL_DELIVERY_FAILURE', 'NETWORK_ERROR', 'DNS_ERROR', name='issue_type'), nullable=False),
    sa.Column('severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='incident_level'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='incident_status'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('log_file_id', sa.Integer(), nullable=True),
    sa.Column('log_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_issue_type'), 'incidents', ['issue_type'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_severity_status', 'incidents', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_source'), 'incidents', ['source'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.String(length=20), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('incident_ref', sa.String(length=20), nullable=True),
    sa.Column('recommended_fixes', sa.Text(), nullable=False),
    sa.Column('troubleshooting_steps', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remediation_incident_created', 'remediations', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_remediations_confidence_score'), 'remediations', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    op.create_index(op.f('ix_remediations_incident_id'), 'remediations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediations_incident_ref'), 'remediations', ['incident_ref'], unique=False)
    op.create_index(op.f('ix_remediations_remediation_id'), 'remediations', ['remediation_id'], unique=True)
    op.create_table('root_cause_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('possible_causes', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rca_confidence_created', 'root_cause_analyses', ['confidence_score', 'created_at'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_confidence_score'), 'root_cause_analyses', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_id'), 'root_cause_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_root_cause_analyses_incident_id'), 'root_cause_analyses', ['incident_id'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('Critical', 'High', 'Medium', 'Low', name='ticket_priority'), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status'), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_incident_id'), 'tickets', ['incident_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index('ix_tickets_priority_status', 'tickets', ['priority', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=True)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('rca_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rca_id'], ['root_cause_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_article_id'), 'knowledge_articles', ['article_id'], unique=True)
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_incident_id'), 'knowledge_articles', ['incident_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_rca_id'), 'knowledge_articles', ['rca_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_title'), 'knowledge_articles', ['title'], unique=False)
    op.create_index('ix_knowledge_category_created', 'knowledge_articles', ['category', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_category_created', table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_title'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_rca_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_incident_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_article_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index('ix_tickets_priority_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_incident_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_root_cause_analyses_incident_id'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_id'), table_name='root_cause_analyses')
    op.drop_index(op.f('ix_root_cause_analyses_confidence_score'), table_name='root_cause_analyses')
    op.drop_index('ix_rca_confidence_created', table_name='root_cause_analyses')
    op.drop_table('root_cause_analyses')
    op.drop_index(op.f('ix_remediations_remediation_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_incident_ref'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_incident_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_confidence_score'), table_name='remediations')
    op.drop_index('ix_remediation_incident_created', table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source'), table_name='incidents')
    op.drop_index('ix_incidents_severity_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_issue_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_source'), table_name='log_entries')
    op.drop_index('ix_log_entries_severity_log_file', table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_severity'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_log_file_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_log_files_uploaded_by'), table_name='log_files')
    op.drop_index('ix_log_files_status_created_at', table_name='log_files')
    op.drop_index(op.f('ix_log_files_status'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_id'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_file_type'), table_name='log_files')
    op.drop_table('log_files')
    op.drop_index(op.f('ix_ai_history_user_id'), table_name='ai_history')
    op.drop_index(op.f('ix_ai_history_id'), table_name='ai_history')
    op.drop_table('ai_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_created_at', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_alerts_type_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_reference_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
